# File: src/core/agent/state.py

from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional
from pydantic import BaseModel, Field


class EmailMessage(BaseModel):
    """Represents a single email message inside a thread."""

    from_: str = Field(..., alias="from")
    timestamp: str
    body: str


class EmailThread(BaseModel):
    """Represents an email conversation thread."""

    thread_id: str
    subject: str
    messages: List[EmailMessage]


class TriageResult(BaseModel):
    """Structured classification of the thread."""

    priority: Literal["low", "medium", "high", "urgent"]
    category: Literal["meeting", "billing", "incident"]
    needs_reply: bool
    rationale: str


class ThreadSummary(BaseModel):
    """Structured summary of the thread."""

    key_points: List[str]
    ask: Optional[str] = None


class DraftReply(BaseModel):
    """Draft reply generated by the agent."""

    subject: str
    body: str


class ActionPayload(BaseModel):
    """Generic payload structure for agent actions."""

    recipient: Optional[str] = None
    subject: Optional[str] = None
    body: Optional[str] = None
    title: Optional[str] = None
    description: Optional[str] = None
    start_time: Optional[str] = None
    end_time: Optional[str] = None
    due_date: Optional[str] = None


class ProposedAction(BaseModel):
    """Action proposed by the agent."""

    type: Literal["send_email", "create_calendar_event", "create_task", "none"]
    label: str
    payload: ActionPayload = Field(default_factory=ActionPayload)
    requires_approval: bool = True


class ProposedActionsResult(BaseModel):
    """Container for multiple proposed actions."""

    actions: List[ProposedAction] = Field(default_factory=list)


class ExecutionEvent(BaseModel):
    """Structured execution trace event for observability."""

    step: str
    status: Literal["pending", "success", "failed"]
    detail: Optional[str] = None

    # Duration of step execution
    duration_ms: Optional[float] = None

    # Optional metadata for debugging
    metadata: Dict[str, Any] = Field(default_factory=dict)


class AgentState(BaseModel):
    """Full state object flowing through the LangGraph workflow."""

    # Input thread
    thread: EmailThread

    # Unique identifier for this workflow execution
    run_id: Optional[str] = None

    # Core outputs produced by nodes
    triage: Optional[TriageResult] = None
    summary: Optional[ThreadSummary] = None
    draft: Optional[DraftReply] = None
    proposed_actions: List[ProposedAction] = Field(default_factory=list)

    # Retrieved long-term memory
    retrieved_preferences: Dict[str, Any] = Field(default_factory=dict)
    retrieved_contact: Dict[str, Any] = Field(default_factory=dict)
    retrieved_org_facts: Dict[str, Any] = Field(default_factory=dict)

    # Human approval state
    approval_status: Literal["pending", "approved", "rejected"] = "pending"

    # Execution trace for observability
    execution_log: List[ExecutionEvent] = Field(default_factory=list)
    # Input
    thread: EmailThread

    # Run metadata
    run_id: Optional[str] = None

    # Core workflow outputs
    triage: Optional[TriageResult] = None
    summary: Optional[ThreadSummary] = None
    draft: Optional[DraftReply] = None
    proposed_actions: List[ProposedAction] = Field(default_factory=list)

    # Retrieved long-term memory for this run
    retrieved_preferences: Dict[str, Any] = Field(default_factory=dict)
    retrieved_contact: Dict[str, Any] = Field(default_factory=dict)
    retrieved_org_facts: Dict[str, Any] = Field(default_factory=dict)

    # Human-in-the-loop status
    approval_status: Literal["pending", "approved", "rejected"] = "pending"

    # Execution / trace breadcrumbs
    execution_log: List[ExecutionEvent] = Field(default_factory=list)